name = "pokemon-game-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[vars]
ENVIRONMENT = "production"

# Production database configuration
[[d1_databases]]
binding = "DB"
database_name = "pokemon-game-db"
database_id = "189590d0-ecbb-43c9-81d7-911f41f5e851"

[env.development]
vars = { ENVIRONMENT = "development" }

# For local development
[[env.development.d1_databases]]
binding = "DB"
database_name = "pokemon-game-db"
database_id = "local-pokemon-game-db"